### ISSUE TITLE
Is this decoder auto calculate the SOF?

### ISSUE THREAD

**Issue by HanalogInstruments** [MROS/jpeg_decoder#1]
Hi,
Is This :  // TODO: 高度跟寬度不確定 
When we don't know the height and width so is auto calculate from the MCU?

**Comment by MROS** [comment]
Sorry, I'm not sure what the comment mean. It's written so many years ago. I think it's weird because the code can read the height and width from SOS. Maybe at that time, I not sure the order of height and width.

Now I removed the comment.
